# postgre datasource
spring:
  datasource:
    url: jdbc:postgresql://dpg-cgd5b7qk728mugdoth00-a.singapore-postgres.render.com/blogjava
    username: smile
    password: ugIiKbfiigBWiRlfKD8Lq0699OZNEihh
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always

# logging sql
logging:
  level:
    org:
      hibernate:
        SQL: debug