# postgre datasource
spring:
  datasource:
    url: jdbc:mysql://containers-us-west-28.railway.app:6699/railway
    username: root
    password: zF01VUmRYJk6QQtxnbFD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# logging sql
logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  app:
    jwtRefreshExpirationMs: 64800000

server:
  error:
    include-stacktrace: never
    include-message: always
