# postgre datasource
spring:
  datasource:
    url: jdbc:mysql://elearning216-cnlt-forum.aivencloud.com:14490/defaultdb
    username: avnadmin
    password: AVNS_m6FKR1IsJJoqP7eyp5A
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# logging sql
logging:
  level:
    org:
      hibernate:
        SQL: warn

jwt:
  app:
    jwtRefreshExpirationMs: 64800000

server:
  error:
    include-stacktrace: never
    include-message: always
