on:
  push:
    branches:
      - main

name: Build jar

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run:
        mvn clean package --file pom.xml
    - uses: ncipollo/release-action@v1
      with:
        name: ${{ env.GITHUB_REF_NAME }}
        tag: ${{ env.GITHUB_REF_NAME }}
        artifacts: "target/E-Learning-0.0.1-SNAPSHOT.jar"
        token: ${{ secrets.GITHUB_TOKEN }}

